### ISSUE TITLE
www.proteomicsml.org vs proteomicsml.org

### ISSUE THREAD

**Issue by makingions** [ProteomicsML/ProteomicsML#152]
### Pre-issue creation checklist

- [X] No duplicates of this issue have already been created.
- [X] This issue does not fit any of the other categories.

### Describe your issue

1. Links to proteomicsml.org don't work, the issue is that the www is required at the moment e.g. see 
![image](https://user-images.githubusercontent.com/48596658/194192381-392a876c-e51b-4f71-ab5a-641aef93becc.png)

2. Links to https://www.proteomicsml.org/ do work. This includes www. so works OK

Suggests DNS record issue that could resolve issues
https://support.duda.co/hc/en-us/articles/4410641737239-Site-not-working-without-WWW

**Comment by RalfG** [comment]
I followed the GitHub documentation to validate the hosting DNS settings, and it seems that the apex domain configuration (`A` file) is working:
```sh
❯ dig PROTEOMICSML.ORG +noall +answer -t A
proteomicsml.org.       0       IN      A       162.255.119.149
```
And the `www` subdomain variant is also working (as far as I understand):
```sh
❯ dig WWW.PROTEOMICSML.ORG +nostats +nocomments +nocmd
;WWW.PROTEOMICSML.ORG.          IN      A
www.proteomicsml.org.   0       IN      CNAME   proteomicsml.github.io.
proteomicsml.github.io. 0       IN      A       185.199.110.153
proteomicsml.github.io. 0       IN      A       185.199.111.153
proteomicsml.github.io. 0       IN      A       185.199.108.153
proteomicsml.github.io. 0       IN      A       185.199.109.153
```
But the `AAAA` setting does not return any results:
```sh
❯ dig PROTEOMICSML.ORG +noall +answer -t AAAA

```

@edeutsch, could you take a look at the domain hosting and check if the `AAAA` record is setup correctly according to the [GitHub docs](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain)? Thanks!

**Comment by edeutsch** [comment]
There was no AAAA record, but I think that is only for IPV6, which I suspect is not the problem?

I fussed around with the A record but I'm not optimistic that it did anything
proteomicsml.org/publication.html
seems to work.
https://proteomicsml.org/publication.html
is a little more spotty.

Maybe testing with wget illuminates the issue?
```
$ wget https://proteomicsml.org/publication.html
--2022-10-07 11:13:50--  https://proteomicsml.org/publication.html
Resolving proteomicsml.org (proteomicsml.org)... 185.199.108.153, 162.255.119.149, 2606:50c0:8000::153
Connecting to proteomicsml.org (proteomicsml.org)|185.199.108.153|:443... connected.
ERROR: no certificate subject alternative name matches
	requested host name ‘proteomicsml.org’.
To connect to proteomicsml.org insecurely, use `--no-check-certificate'.

$ wget https://www.proteomicsml.org/publication.html
--2022-10-07 11:14:11--  https://www.proteomicsml.org/publication.html
Resolving www.proteomicsml.org (www.proteomicsml.org)... 185.199.108.153, 185.199.111.153, 185.199.110.153, ...
Connecting to www.proteomicsml.org (www.proteomicsml.org)|185.199.108.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 45378 (44K) [text/html]
Saving to: ‘publication.html’

publication.html                   100%[===============================================================>]  44.31K  --.-KB/s    in 0.01s   

2022-10-07 11:14:11 (3.19 MB/s) - ‘publication.html’ saved [45378/45378]
```

I'm wondering if maybe it is a SSL cert issue?
I dunno, I've always struggled with getting the root domain to work properly.

**Comment by edeutsch** [comment]
So I am seeing this:
```
wget http://proteomicsml.org/publication.html - redirected and works
wget http://www.proteomicsml.org/publication.html - works
wget https://www.proteomicsml.org/publication.html - works
wget https://proteomicsml.org/publication.html - FAILS

ERROR: no certificate subject alternative name matches
	requested host name ‘proteomicsml.org’.
To connect to proteomicsml.org insecurely, use `--no-check-certificate'.
```

I don't know how to fix.

**Comment by makingions** [comment]
Just a quick comment that the reason I logged this issue was that internal links within the proteomicsml.org website/tutorial etc sometimes failed to load webpages, leading to an occasional poor user experience for an awesome resource. I haven't thoroughly tested so don't know the full impact.

As a workaround while the technical issue for links without www is being resolved maybe it's possible to programatically update links to contain www. in all the instances? 

I just wanted to flag this for clarity i.e. some internal links within proteomicsml.org sometimes fail due to this issue and there might be a workaround in the meantime. BW

**Comment by edeutsch** [comment]
thank you for the reports!

@RalfG would you be able to update the hyperlinks on the page https://www.proteomicsml.org/contributing.html that currently point to proteomicsml.org to point to www.proteomicsml.org instead?

**Comment by RalfG** [comment]
After updating some of the DNS settings, it seems that the issue has been resolved. A redirect from apex to www prevented GitHub's SSL certificate system from working properly. The redirect is now managed by GitHub pages itself and @edeutsch's wget tests seem to work now. 

@makingions, thanks for reporting!
