### ISSUE TITLE
Should the website refer to the published paper rather then the preprint?

### ISSUE THREAD

**Issue by magnuspalmblad** [ProteomicsML/ProteomicsML#175]
### Pre-issue creation checklist

- [X] No duplicates of this issue have already been created.
- [X] This issue does not fit any of the other categories.

### Describe your issue

Since the article describing the ProteomicML resource is now published in _Journal of Proteome Research_, should the [website](https://proteomicsml.org/) refer to the [published article](https://pubs.acs.org/doi/10.1021/acs.jproteome.2c00629) rather than the preprint? The journal article is Open Access, so anyone can access it.

**Comment by RobbinBouwmeester** [comment]
@RalfG can you fix this?
